# vim: fdm=marker
[ftplugin]
_ = '''
  let g:ale_fixers = [
  \   'remove_trailing_lines',
  \   'trim_whitespace',
  \]
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_fix_on_save = 1
  let g:airline#extensions#ale#enabled = 1
  let g:ale_linters = {
  \ 'java': [],
  \}
  let g:ale_fixers = {
  \ 'java': [
    \ 'remove_trailing_lines',
    \ 'trim_whitespace',
  \ ],
  \}
'''

[[plugins]]
repo = 'sheerun/vim-polyglot'

# {{{ typescript
[[plugins]]
repo = 'mhartington/nvim-typescript'

[[plugins]]
repo = 'Quramy/tsuquyomi'
hook_add = '''
  let g:tsuquyomi_completion_detail = 1 " may be slow
'''
# }}}

#{{{ html
[[plugins]]
repo = 'valloric/MatchTagAlways'
#}}}

#{{{ js
[[plugins]]
repo = 'ternjs/tern_for_vim'
build = 'sudo npm install -g tern'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
#}}}

[[plugins]]
repo = 'wellle/tmux-complete.vim'
hook_add = '''
  let g:tmuxcomplete#trigger = ''
'''

[[plugins]]
repo = 'Shougo/neco-vim'
depends = 'Shougo/deoplete.nvim'

[[plugins]]
repo= 'PotatoesMaster/i3-vim-syntax'
