# vim: fdm=marker
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  let g:rehash256 = 1
  colorscheme molokai
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'powerlineish_mod'
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 0
  let g:airline_left_sep = ''
  let g:airline_right_sep = ''
  let g:airline_left_alt_sep = '|'
  let g:airline_right_alt_sep = '|'
  let g:airline#extensions#syntastic#enabled = 1
  let g:airline#extensions#branch#enabled = 1
  let g:airline#extensions#hunks#enabled = 0
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
