# vim: fdm=marker
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  autocmd User fugitive
    \ if fugitive#buffer().type() =~# '^\%(tree\|blob\)$' |
    \   nnoremap <buffer> .. :edit %:h<CR> |
    \ endif

  autocmd BufReadPost fugitive://* set bufhidden=delete
'''

[[plugins]]
repo = 'shumphrey/fugitive-gitlab.vim'
hook_add = '''
  let g:fugitive_gitlab_domains = ['https://gitlab.beilich.de']
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'ludovicchabant/vim-lawrencium'

[[plugins]]
repo = 'mhinz/vim-signify'
hook_add = '''
  let g:signify_vcs_list = [ 'hg' ]
'''
